function RunAllActogramData(CurDir, ActogramTimeBin, OnsetFittingDay, OnsetFittingDayOffset, LightPulseDuration, SensitivityBinWidth, R2Cutoff, RMSECutoff)

close all;

foldernameCell = {'A2_KO', 'A2_WT', 'A3_KO', 'A4_WT', 'C2_KO', 'C2_WT'};
foldername = string(foldernameCell);

filenameA2KOCellHeader = {'A2-29-1',...
				'A2-30-2',...
				'A2-31-3',...
				'A2-32-4',...
				'A2-33-5',...
				'A2-36-6'};
				%'A2-37-7',...
				%'A2-38-8',...
				%'A2-39-9',...
			
filenameA2WTCellHeader = {'A2-43-11',...
				'A2-44-12',...
				'A2-45-13',...
				'A2-46-14',...
				'A2-47-15'};

filenameA3KOCellHeader = {'A3-57-1',...
				'A3-58-2',...
				'A3-59-3',...
				'A3-61-5',...
				'A3-66-8',...
				'A3-67-9',...
				'A3-71-11',...
				'A3-79-16',...
				'A3-80-17'};
				%'A3-64-6',...
				%'A3-73-13',...

filenameA4WTCellHeader = {'A4-85-1',...
				'A4-86-2',...
				'A4-87-3',...
				'A4-88-4',...
				'A4-89-5',...
				'A4-92-6',...
				'A4-95-9',...
				'A4-96-10',...
				'A4-99-11',...
				'A4-100-12',...
				'A4-101-13',...
				'A4-102-14',...
				'A4-103-15'};
				%'A4-93-7',...

filenameC2KOCellHeader = {'C2-155-11',...
				'C2-156-12',...
				'C2-158-14',...
				'C2-159-15',...
				'C2-160-16',...
				'C2-161-17'};

filenameC2WTCellHeader = {'C2-141-1',...
				'C2-142-2',...
				'C2-144-3',...
				'C2-145-4',...
				'C2-146-5',...
				'C2-147-6',...
				'C2-148-7'};

filenameAllCellHeader = {filenameA2KOCellHeader, filenameA2WTCellHeader, filenameA3KOCellHeader, filenameA4WTCellHeader, filenameC2KOCellHeader, filenameC2WTCellHeader};

Genotype = {'Npas4--', 'Npas4++', 'Npas4--', 'Npas4++', 'Npas4--', 'Npas4++'};

NumFilesInFolders = zeros(1,size(foldernameCell,2));
for i=1:size(foldernameCell,2)
	NumFilesInFolders(i) = size(filenameAllCellHeader{i},2);
end

for i=1:size(foldernameCell,2)
	filenameHeader = string(filenameAllCellHeader{i});
	cnt=0;

	% Number of mice in each folder	
	for j=1:NumFilesInFolders(i)

		[i j filenameHeader(j)]
		
		ActogramFilename = sprintf('%s_Counts.csv', filenameHeader(j));
		cd(strcat(CurDir, foldername(i)));
		pwd

		LightInfoFilename = sprintf('../LightPulseInfo_%s.csv', foldername(i))
		fid = fopen(LightInfoFilename);
		LightPulseInfo = textscan(fid,'%s %d %d %d %d %d %d');
		fclose(fid);

		LPstr = string(LightPulseInfo{1});
		LPstart = find(LPstr =='LP1');
		NumLightPulses = size(LightPulseInfo{1},1) - LPstart + 1;

		[max_row, dp] = IterativeWaveletAnalysisOfActogram(string(Genotype(i)), ActogramFilename, LightInfoFilename, ActogramTimeBin, OnsetFittingDay, OnsetFittingDayOffset, LightPulseDuration, NumLightPulses, SensitivityBinWidth, R2Cutoff, RMSECutoff);

		if cnt==0
			max_row_all = max_row;
			dp_all = dp;
		else
			max_row_all = [max_row_all max_row];
			dp_all = [dp_all dp];
		end
		cnt = cnt+1;
		close all;
	end

	dlmwrite(sprintf('%s_PRC_Data.csv', char(foldername(i))), dp_all, 'delimiter', '\t');%, 'precision', 5);
	
end

